# 1. This line tells the Podfile where to find Flutter's helper functions
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 2. This command actually installs your plugins (Firebase, etc.)
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # 3. This ensures every sub-library also targets iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end