platform :ios, '15.0' # <--- This is the magic line

import_with_parent('../../node_modules/expo-modules-autolink/scripts/ios/autolinking_manager.rb') if File.exist?('../../node_modules/expo-modules-autolink/scripts/ios/autolinking_manager.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # This ensures every pod also uses iOS 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end